#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname "$(realpath "$0")")"/..
DOTFILES_ROOT=$(pwd -P)

source script/utils.sh

info "install"

# find the installers and run

find . -name install.sh | while read -r installer; do
  source "$installer"
done

success "install"
