[default_session]
startup_command = "ls"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "base"
path = "~"
startup_command = "ls"
preview_command = "bat --color=always ~"

[[session]]
name = "config-sesh"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "config-dotfiles"
path = "~/.dotfiles"
startup_command = "nvim"

[[session]]
name = "config-nvim"
path = "~/.config/nvim"
startup_command = "nvim init.lua"
preview_command = "bat --color=always ~/.config/nvim/init.lua"

[[session]]
name = "config-tmux"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"

[[session]]
name = "config-alacritty"
path = "~/.config/alacritty"
startup_command = "nvim alacritty.toml"
preview_command = "bat --color=always ~/.config/alacritty/alacritty.toml"

[[session]]
name = "config-aerospace"
path = "~/.config/aerospace"
startup_command = "nvim aerospace.toml"
preview_command = "bat --color=always ~/.config/aerospace/aerospace.toml"

[[session]]
name = "config-zshrc"
path = "~"
startup_command = "nvim .zshrc"
preview_command = "bat --color=always ~/.zshrc"

[[session]]
name = "config-ssh"
path = "~/.ssh"
startup_command = "nvim config"
preview_command = "bat --color=always ~/.ssh/config"

[[session]]
name = "ssh-cs528"
path = "~"
startup_command = "ssh cs528"
preview_command = "show-ssh-conf cs528 | bat"

[[session]]
name = "ssh-v100"
path = "~"
startup_command = "ssh wxk-6.23"
preview_command = "show-ssh-conf wxk-6.23"

[[session]]
name = "ssh-Jetson-AGX-Orin"
path = "~"
startup_command = "ssh AGXOrin"
preview_command = "show-ssh-conf AGXOrin | bat"
